### ISSUE TITLE
wemo server returns error messages and empty page

### ISSUE THREAD

**Issue by yaccin** [iancmcc/ouimeaux#103]
I just installed ouimeaux on my raspberry pi 2 (raspian, debian basically) and get these error messages when starting the server:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/pywsgi.py", line 371, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/pywsgi.py", line 575, in handle_one_request
    self.handle_one_response()
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/pywsgi.py", line 690, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0xe80030: _close_when_done(<socket at 0xd00b30 fileno=[Errno 9] Bad file desc, ('10.0.1.216', 50818))> failed with UnicodeError

wemo list works fine. The website from the server looks like this: https://www.dropbox.com/s/l909mnj7y2q31qi/Screenshot%202015-09-22%2016.43.02.png?dl=0

**Comment by markuskonrad** [comment]
Hi,
same here. `wemo` cmd-line works, api via REST (at least GET) also works and returns JSON-String in Chrome. WebApp does not show any content (only header 'Quimeaux' and footer 'copyright 2013 Ian McCracken')

BTW: Is there a way to "Restart" the server? Or is this done after updating the config file?
Thanks,
Markus

**Comment by PLNech** [comment]
Hi, 

I am experiencing the same error message with Ajenti Server on Debian:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg/gevent/server.py", line 130, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 371, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 575, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/pymodules/python2.7/ajenti/http.py", line 25, in handle_one_response
    return SocketIOHandler.handle_one_response(self)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 690, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
```

Maybe there is a common problem to our two situations, potentially linked to `gevent`?

**Comment by PLNech** [comment]
After more investigation on the affected system, and identification of the [exact error](https://github.com/gevent/gevent/blob/master/gevent/pywsgi.py#L695), I was able to pinpoint the issue to **Socket.IO**'s `transports.py` and `handler.py`, which both contained the following line:

            ("Access-Control-Max-Age", 3600),

changing it to

            ("Access-Control-Max-Age", "3600"),

successfully restored ajenti panel's functionality. I am pretty sure that it will solve as well @dawnson's issue.

@iancmcc, do you think this should be reported to socketio/gevent maintainers? To me the problem seems beyond the reach of either Ajenti or ouimeaux.

**Comment by iancmcc** [comment]
Doesn't seem out of the question, but I'll try to fix it in ouimeaux for
the time being. Thanks for investigating.

**Comment by sypyguy** [comment]
Thank you for looking into this, I think I am having the same issue
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/pywsgi.py", line 792, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/pywsgi.py", line 779, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/pywsgi.py", line 768, in process_result
    for data in self.result:
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/subscribe.py", line 77, in _handle
    ('Connection', 'close')
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-armv7l.egg/gevent/pywsgi.py", line 690, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Content-Length', 41)
{'CONTENT_LENGTH': '132',
 'CONTENT_TYPE': 'text/xml; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_HOST': '192.168.1.84:8989',
 'HTTP_NT': 'upnp:event',
 'HTTP_NTS': 'upnp:propchange',
 'HTTP_SEQ': '0',
 'HTTP_SID': 'uuid:19167b78-1dd2-11b2-87d1-fb757412bba9',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.1.11',
 'REMOTE_PORT': '3491',
 'REQUEST_METHOD': 'NOTIFY',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'raspberrypi',
 'SERVER_PORT': '8989',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.1 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x76d1c0d0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x159a8b8>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with UnicodeError

**Comment by Go3Team** [comment]
I've got the same issue as above:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b6-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 846, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b6-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 833, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b6-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 822, in process_result
    for data in self.result:
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux/subscribe.py", line 77, in _handle
    ('Connection', 'close')
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b6-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 740, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Content-Length', 41)
{'CONTENT_LENGTH': '142',
 'CONTENT_TYPE': 'text/xml; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_HOST': '10.10.0.2:8989',
 'HTTP_NT': 'upnp:event',
 'HTTP_NTS': 'upnp:propchange',
 'HTTP_SEQ': '18',
 'HTTP_SID': 'uuid:ba892d64-1dd1-11b2-8e42-90bb1280f437',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '10.10.0.3',
 'REMOTE_PORT': '4278',
 'REQUEST_METHOD': 'NOTIFY',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'wemo',
 'SERVER_PORT': '8989',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.1 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fa14357c1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7fa13df738d8>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with UnicodeError

**Comment by delwinbest** [comment]
Same issue here running latest version of Wemo firmware. 
("Access-Control-Max-Age", "3600") "Fix" doesnt work

Error output:
WeMo Motion state is on
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1rc1-py2.7-linux-armv6l.egg/gevent/pywsgi.py", line 846, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1rc1-py2.7-linux-armv6l.egg/gevent/pywsgi.py", line 833, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1rc1-py2.7-linux-armv6l.egg/gevent/pywsgi.py", line 822, in process_result
    for data in self.result:
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/subscribe.py", line 77, in _handle
    ('Connection', 'close')
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1rc1-py2.7-linux-armv6l.egg/gevent/pywsgi.py", line 740, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Content-Length', 41)

**Comment by delwinbest** [comment]
Found the problem & fix. 
For me I was able to cast the 'Content-Length' value as a string in subscribe.py and get Domoticz monitoring example working with this change (wemo FW version is WeMo_WW_2.00.9896.PVT-OWRT-SNS)

Steps on raspbian:
 vi /usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/subscribe.py
change line 76 from:
('Content-Length', len(SUCCESS)),
to:
('Content-Length', str(len(SUCCESS))),

**Comment by sanzenwin** [comment]
Thanks,it works!

**Comment by sstangle73** [comment]
This didnt fix it for me.. still get the following stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 411, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 626, in handle_one_request
    self.handle_one_response()
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 741, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0xc41da0: _close_when_done(<socket at 0xd8d910 fileno=[Errno 9] Bad file desc, ('192.168.1.7', 58250))> failed with UnicodeError
```

**Comment by richardj311** [comment]
There's possibly another occurrence of code similar to Content-Length that was not addressed by #103. Prior to #103, I was experiencing the UnicodeError issue for my two Makers when (1) executing "wemo status", (2) when starting the server, and (3) with any utilization of the server. Both (1) and (2) have been addressed by the fix for #103. However, I get the stack trace provided by sstangle73 when I attempt to use the server (e.g., open the web app).

p.s. I'm new to GitHub and am not sure of the protocol for issue discussion/reporting (I checked GitHub Help); given that issue #103 is closed, is further discussion required to occur in an new issue?

**Comment by LemonTVnz** [comment]
https://github.com/ajenti/ajenti/issues/815
gevent is broken
install the beta which works

`sudo easy_install -U gevent==1.1b4`

**Comment by flare04** [comment]
Tried installing gevent 1.1b4 same issue. Gone back to gevent 1.1.1. ouimeaux 0.7.9.post0 installed.  applied the subscribe.py change above. 
Still getting this error

192.168.1.200 - - [2016-05-22 17:33:16] "GET /static/partials/landing.html HTTP/1.1" 304 186 0.023587
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 778, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0xb6058da0L: _handle_and_close_when_done(<bound method SocketIOServer.handle of <SocketIOSe, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0xb56d4b10L fileno=[Errno 9] Bad file )> failed with UnicodeError

**Comment by joshzitting** [comment]
I'm having this issue too. Any updates? I am running it on ubuntu mate on a pi 3. I can also try it on a normal ubuntu installation if needed?

**Comment by iancmcc** [comment]
Please try this on version 0.8.0, which includes a gevent upgrade and several other related fixes. If it's still broken, let's reopen the ticket.

**Comment by jansel** [comment]
I am still experiencing this issue on the latest development version.  The problem seems to be in `gevent-socketio==0.3.6`.

The following hacky fix worked for me:
```
cd $(python -c 'import socketio, os; print(os.path.dirname(socketio.__file__))')
sed -i.bak 's@-Max-Age", 3600@-Max-Age", "3600"@' handler.py
sed -i.bak 's@-Max-Age", 3600@-Max-Age", "3600"@' transports.py
```

This is fixed by [this commit](https://github.com/abourget/gevent-socketio/commit/12da9667deba432d8917129afab1daa86c20ec84#diff-7d17ce714151a7838205e82575cb099bL77) in gevent-socketio, which does not seem to have been uploaded to pypi yet.
